### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'units'

### ISSUE THREAD

**Issue by ToxicGigante** [Jimm1432/Rush-Royale-Bot#12]
I have like no idea of what I'm doing please let me know what i missed

![Capture](https://github.com/Jimm1432/Rush-Royale-Bot/assets/150766252/63438249-4188-47a6-acc8-ecad718e487e)

**Comment by ToxicGigante** [comment]
I really have no idea what I'm doing wrong. I deleted the directory and re-did it with your git address and then installed the bot and launched and still the same error

**Comment by ToxicGigante** [comment]
i figured it out i needed to make a fix to the units scrip into "all_units"

**Comment by Jimm1432** [comment]
You need a folder called units in the main folder. most likely a permissions issue caused it to not be made.
