### ISSUE TITLE
The bot will think a demon hunter is harlequin and merge them

### ISSUE THREAD

**Issue by ToxicGigante** [Jimm1432/Rush-Royale-Bot#13]
in running the bot the Harlequin detection at higher levels is needed.

**Comment by Jimm1432** [comment]
You will get units with close colours having trouble merging and you should use the units png the matches your talents. You can also grab a fresh png from the OCR folder of the unit your having trouble with when the bot is running, on whatever floor your doing (backgrounds affect it). Make sure you grab a clean rank 1 png and resize it by pixels 90x90, I like to trim the edges to match the others but I think you could get away with just resizing. Throw the finished png into the all_units folder.

**Comment by ToxicGigante** [comment]
it seems to now not prioritize that Demon Hunter is the dps unit It is weird that even though demon hunter is being prioritized it's not being used well. 
![bot_feed_emulator-5554](https://github.com/Jimm1432/Rush-Royale-Bot/assets/150766252/d9a810b7-6091-4414-ba6a-bdd6b9b421a7)

**Comment by ToxicGigante** [comment]
it just keeps merging everything no dps priority

**Comment by Jimm1432** [comment]
That's because special units have priority, ie mime, harlequin, dryad. I
would like to start again with the way it merges everything because it's so
cluttered and needs simplicity.

I'm going to work on it soon and I want to speed it up because it builds up
so much mana.
