### ISSUE TITLE
the picture freezes in bluestacks

### ISSUE THREAD

**Issue by Dam04ka** [Jimm1432/Rush-Royale-Bot#17]
When I launch the bot, the picture in bluestacks freezes. Meanwhile, the bot is working, and this can be seen in the replays of the game. How can I see in real time that the bot is working?

**Comment by Jimm1432** [comment]
That's a Bluestacks issue nothing to dop with the bot.

I would suggest Adding more RAM to the instance In Bluestacks settings.

**Comment by goooooone** [comment]
Run BlueStacks multi-instance manager and run bluestacks pie 64-bit. It's work for me.

> When I launch the bot, the picture in bluestacks freezes. Meanwhile, the bot is working, and this can be seen in the replays of the game. How can I see in real time that the bot is working?
