### ISSUE TITLE
launch_gui.bat don't open 

### ISSUE THREAD

**Issue by kast0l** [Jimm1432/Rush-Royale-Bot#6]
What's is problem?

**Comment by hard2carry** [comment]
Src\gui.py is missing in the newest release

**Comment by kast0l** [comment]
> Src\gui.py отсутствует в новейшей версии

how do i run the gui then?

**Comment by hard2carry** [comment]
You can restore an [older version](https://github.com/Jimm1432/Rush-Royale-Bot/blob/6329668fcb3de84f88fa208b5fa3c8e00eabfde5/Src/gui.py) and place it in the src folder or wait for Jimm to fix it.
Idk if it's a permanent solution but at least it's working again for me.

**Comment by Jimm1432** [comment]
Sorry guys my laptop died on me during updating the repo, I'm not sure what was lost and I lost my whole local repo that had my updates i'd been working on for the last month.

I've got a new laptop and ill try to get back on top of everything.
