### ISSUE TITLE
Error running launch_gui.bat

### ISSUE THREAD

**Issue by Riscon** [Jimm1432/Rush-Royale-Bot#7]
Hi I get the following error while running the launch_gui.bat:

C:\Users\User\Downloads\Rush-Royale-Bot_Jimm>call .bot_env\Scripts\activate.bat
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Rush-Royale-Bot_Jimm\Src\gui.py", line 262, in <module>
    bot_gui = RR_bot()
  File "C:\Users\User\Downloads\Rush-Royale-Bot_Jimm\Src\gui.py", line 28, in __init__
    self.ads_var, self.buy_var, self.pve_var, self.shaman_var, self.maps_var, self.mana_vars, self.floor = create_options(self.frames[0], self.config)
  File "C:\Users\User\Downloads\Rush-Royale-Bot_Jimm\Src\gui.py", line 188, in create_options
    buy_var = IntVar(value=user_buy)
UnboundLocalError: local variable 'user_buy' referenced before assignment

Edit: I am running
C:\Users\User>python --version
Python 3.9.13

**Comment by Riscon** [comment]
So I've found out the problem lies within your addings of "Use Maps" and "Buy Store".
I've commented these parts out and it starts up now.

**Comment by mridvanbas** [comment]
how did you do that?

> So I've found out the problem lies within your addings of "Use Maps" and "Buy Store". I've commented these parts out and it starts up now.

**Comment by Jimm1432** [comment]
Half added feature I hadn't commented out, Is corrected now.
